"""English names for Battle Space's classes, spells and special moves.

The Japanese names are the game's own, read from its ROM into
`battlespace_tables`; these are this project's translation, in the same order.
"""

from typing import Final

CLASS_ENGLISH: Final = (
    "Sorcerer King",
    "Dragon Knight",
    "Demon Warrior",
    "Karateka",
    "Dragon",
    "Lich",
    "High Master",
    "Shogun",
    "Lord",
    "Samurai",
    "Martial Artist",
    "Knight",
    "Paladin",
    "Elf",
    "Eliminator",
    "Ninja",
    "Kunoichi",
    "Pugilist",
    "Barbarian",
    "Valkyrie",
    "Sword Master",
    "Myrmidon",
    "Dwarf",
    "Headhunter",
    "Berserker",
    "Warrior",
    "Assassin",
    "Pirate",
    "Monk",
    "Bishop",
    "Cleric",
    "Druid",
    "Rune Master",
    "Necromancer",
    "Fallen Monk",
    "Sorcerous Head",
    "Phantom",
    "Wraith",
    "Shrine Maiden",
    "Fortune Teller",
    "Prophet",
    "Orc Mage",
    "Magician",
    "Golem",
    "Giant",
    "Big Man",
    "Heavy Warrior",
    "Light Warrior",
    "Troll",
    "Ogre",
    "Grizzly",
    "Orc Leader",
    "Orc",
    "Bard",
    "Ranger",
    "Archdemon",
    "Vampire",
    "Demon",
    "Rogue",
    "Corpse Master",
    "Magic Soldier",
    "Half-Elf",
    "Familiar",
    "Imp",
    "Wyvern",
    "Wrestler",
    "Master Thief",
    "Thief",
    "Broker",
    "Merchant",
    "Wild Man",
    "Fighter",
    "Werewolf",
    "Wolf",
    "Sorcerer",
    "Mage",
    "Wizard",
    "Witch",
    "Sage",
    "Conjurer",
    "Sorceress",
    "Shaman",
    "Warrior Monk",
    "Little Monk",
    "Evil Mage",
    "Mini Devil",
    "Spirit",
    "Little Devil",
    "Gargoyle",
    "Ripper",
    "Metal Armour",
    "Mini Dragon",
    "Living Armour",
    "Jester",
    "Bandit",
    "Lesser Bear",
    "Thug",
    "Slime",
)

SPELL_ENGLISH: Final = (
    "Strength",
    "Shield",
    "Cure",
    "Resist",
    "Fog",
    "Refresh",
    "Holy Force",
    "Weak",
    "Slow",
    "Bombs",
    "Thunder",
    "Fire",
    "Tornado",
    "Meteor",
)

SPECIAL_ENGLISH: Final = (
    "Bite",
    "Flurry of blows",
    "Flurry of slashes",
    "Charge",
    "Life drain",
    "Breath",
    "Critical hit",
    "Healing",
)
